INSERT INTO products SET idType = 4, name = "Artésunate, 60mg, Injectable", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 150, unit = "1 Amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Quinine Bichlorhydrate, 300mg/ml, 2ml", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 22, unit = "1 Amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Ceftriaxone 1g, Vial, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 0.32, unit = "1 Vial - 1", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Dexamethasone sodium phosphate, 4mg/ml, 1ml", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 0.48, unit = "1 Ampoule - 10", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Gentamycine, 40mg/ml, 2ml, Amp", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 6, unit = "1 Ampoule - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Oxytocine, 10UI/ml, 1ml, Amp", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 9.5, unit = "1 Ampoule - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Dextrose (Glucose), 50%, 50ml,", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 13, unit = "1 Baxter - 20", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Ciprofloxacine, 2mg/ml flacon", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 50, unit = "Flacon - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Metronidazole 500 mg/100 ml, inj, flacon", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 50, unit = "Flacon - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Epinéphrine (Adrenaline), 1mg/ml, 1ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 1.5, unit = "1 Ampoule - 10", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Ampicilline, 1g, Vial, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 17, unit = "1amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Atropine, 1mg/ml, 1ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 6, unit = "1amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Diazepam, 5mg/ml, 2ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 1.5, unit = "1amp - 10", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Diclofenac 25mg/ml, 3ml, Amp, Unité ", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 5, unit = "1amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Eau pour injection, 10ml, Vial, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 6, unit = "1amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Furosemide, 10mg/ml, 2ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 6, unit = "1amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Hydrocortisone sodium succinate, 100mg, Vial, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 50, unit = "1amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Methylergometrine maleate, 0.2mg/ml, 1ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 2.5, unit = "1amp - 10", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Métoclopramide chlorhydrate, 5mg/ml, 2ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 9, unit = "1amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Penicilline Benzathine, 2,4MUI, Vial, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 17, unit = "1amp - 50", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Phenobarbital sodique, 100mg/ml, 2ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 8.5, unit = "1amp - 10", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Phytomenadione (Vitamine K1), 10mg/ml, 1ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 7, unit = "1amp - 30", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Pyridoxine, 50mg/ml, 2ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 0.5, unit = "1amp - 10", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Salbutamol, 0,5mg/ml, 1ml, Amp, Unité", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 11, unit = "1amp - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "Sulfate de Magnésium, 500mg, 10ml, Amp", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 13, unit = "1 Ampoule - 10", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "CEFOTAXIME sodique, éq. 1g base, fl.", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 32, unit = "Flacon - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "CLOXACILLINE sodique, éq. 500 mg base, poudre, fl. IV", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 22, unit = "Flacon - 100", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "CHLORAMPHENICOL, 1 g, poudre,  fl.", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 35, unit = "Flacon - 50", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "PARACETAMOL (acétaminophène), 10 mg/ml, 100 ml, fl.", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 20, unit = "Flacon - 10", timestamp = 1704187969;
INSERT INTO products SET idType = 4, name = "TRAMADOL chlorhydrate, 50 mg/ml, 2 ml, amp.", nameOfType =  "Médicaments parenteraux", inStock = 0, price = 2.55, unit = "ampoule - 10", timestamp = 1704187969;
